name: Minify JS Files

on:
  push:
    branches:
      - main

jobs:
  minify_and_obfuscate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Minify and Obfuscate JS Files
        run: | 
          rm -rf .github
          find . -name "*.js" ! -name "*.json" -exec sh -c 'npx terser {} -o {}\;

      - name: Create Tag
        id: create_tag
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m 'Automatically Packaged for Release'
          git tag v1.0.$(date '+%Y%m%d%H%M%S')
        if: success()

      - name: Push Tag
        if: success()
        run: |
          git push --tags https://${{ secrets.GH_TOKEN }}@github.com/vrkersey/aem_extension.git
