name: Release on manifest.json Change

on:
  push:
    paths:
      - 'manifest.json'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Get version from manifest.json
      id: get_version
      run: |
        version=$(jq -r '.version' manifest.json)
        echo "Version: $version"
        echo "version=$version" >> $GITHUB_ENV

    - name: Create ZIP file excluding .github directory
      run: |
        zip_name="chrome-extension-${{ env.version }}.zip"
        zip -r $zip_name . -x ".github/*"
        echo "zip_name=$zip_name" >> $GITHUB_ENV

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: v${{ env.version }}
        release_name: Chrome Extension v${{ env.version }}
        draft: false
        prerelease: false

    - name: Upload ZIP to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.zip_name }}
        asset_name: ${{ env.zip_name }}
        asset_content_type: application/zip
