name: Minify and Obfuscate JS Files

on:
  push:
    branches:
      - main

jobs:
  minify_and_obfuscate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set Working Directory
        run: |
          cd $GITHUB_WORKSPACE/aem_extension

      - name: Install Dependencies
        run: npm install

      - name: Minify and Obfuscate JS Files
        run: find . -name "*.js" ! -name "*.json" -exec sh -c 'npx terser {} -o {}.min && npx javascript-obfuscator {}.min --output {}.obfuscated.js' \;

      - name: Create Tag
        id: create_tag
        run: git tag $(date '+%Y%m%d%H%M%S')
        if: success()

      - name: Push Tag
        if: success()
        run: git push origin ${{ steps.create_tag.outputs.tag }}
