# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Dependencies
      run: npm install

    - name: Minify and Obfuscate JS Files
      run: |
          TIMESTAMP=$(date '+%Y%m%d%H%M%S')
          find . -name "*.js" ! -name "*.json" -exec sh -c 'npx terser {} -o {} && npx javascript-obfuscator {} --output {} ' \;

    - name: Create Tag
      id: create_tag
      run: git tag $TIMESTAMP
      if: success()

    - name: Push Tag
      if: success()
      run: git push origin ${{ steps.create_tag.outputs.tag }}
